services:
  minio:
    image: minio/minio:RELEASE.2024-05-01T01-11-10Z
    command:
      - server
      - /data
      - --address=:9000
      - --console-address=:9001
    restart: always
    volumes:
      - minio_data:/data
    env_file:
      - path: compose.minio.env
        required: true
    ports:
      - 9000:9000
      - 9001:9001

volumes:
  minio_data:
