services:
  mysql:
    image: mysql:8.4.2
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    restart: always
    volumes:
      - mysql_data:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    ports:
      - 3306:3306
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "mysqladmin --silent -h localhost -u root -p'${MYSQL_ROOT_PASSWORD}' ping", # https://github.com/docker-library/mysql/issues/930
        ]
      interval: 5s
      timeout: 5s
      retries: 10

volumes:
  mysql_data:
