services:
  redis:
    image: redis:7.2
    command:
      - --maxmemory
      - 1gb
      - --maxmemory-policy
      - allkeys-lru
      - --requirepass
      - ${REDIS_PASSWORD} # https://docs.docker.com/compose/compose-file/12-interpolation/
    restart: always
    volumes:
      - redis_data:/data # https://github.com/docker-library/redis/issues/140
    ports:
      - 6379:6379

volumes:
  redis_data:
