services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.14.3
    restart: always
    volumes:
      - elasticsearch_data:/usr/share/elasticsearch/data
    environment:
      - node.name=elasticsearch
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
      - ELASTIC_PASSWORD=${ELASTIC_PASSWORD}
      - xpack.security.enabled=true
      - xpack.security.http.ssl.enabled=false
    ports:
      - 9200:9200
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "curl -s http://localhost:9200 | grep -q 'missing authentication credentials'",
        ]
      interval: 10s
      timeout: 10s
      retries: 120

  prepare-kibana: # https://github.com/elastic/elasticsearch/blob/1fad3347b7077c5bcf534b5c5332ad2c92e9f875/docs/reference/setup/install/docker/docker-compose.yml
    image: docker.elastic.co/elasticsearch/elasticsearch:8.14.3
    user: root
    volumes:
      - kibana_data:/usr/share/kibana/data
    command: >
      bash -c '
        if [ -f /usr/share/kibana/data/.kibana-initialized ]; then
          echo "Skip kibana_system password initialization"
          exit 0
        else
          touch /usr/share/kibana/data/.kibana-initialized
        fi
        if [ x${ELASTIC_PASSWORD} == x ]; then
          echo "Missing the ELASTIC_PASSWORD environment variable"
          exit 1
        elif [ x${KIBANA_PASSWORD} == x ]; then
          echo "Missing the KIBANA_PASSWORD environment variable"
          exit 1
        fi
        until curl -s -X POST -u "elastic:${ELASTIC_PASSWORD}" -H "Content-Type: application/json" http://elasticsearch:9200/_security/user/kibana_system/_password -d "{\"password\":\"${KIBANA_PASSWORD}\"}" | grep -q "^{}"; do sleep 10; done
      '
    depends_on:
      elasticsearch:
        condition: service_healthy

  kibana:
    image: docker.elastic.co/kibana/kibana:8.14.3
    restart: always
    volumes:
      - kibana_data:/usr/share/kibana/data
    environment:
      - SERVERNAME=kibana
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
      - ELASTICSEARCH_USERNAME=kibana_system
      - ELASTICSEARCH_PASSWORD=${KIBANA_PASSWORD}
    ports:
      - 5601:5601
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "curl -s -I http://localhost:5601 | grep -q 'HTTP/1.1 302 Found'",
        ]
      interval: 10s
      timeout: 10s
      retries: 120
    depends_on:
      prepare-kibana:
        condition: service_completed_successfully

volumes:
  elasticsearch_data:
  kibana_data:
