services:
  minio:
    image: minio/minio:RELEASE.2024-07-31T05-46-26Z
    command:
      - server
      - /data
      - --address=:9000
      - --console-address=:9001
    restart: always
    volumes:
      - minio_data:/data
    environment:
      - MINIO_ROOT_USER=${MINIO_ROOT_USER}
      - MINIO_ROOT_PASSWORD=${MINIO_ROOT_PASSWORD}
      - MINIO_UPDATE=off
    ports:
      - 9000:9000
      - 9001:9001
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "mc ready local", # https://github.com/minio/minio/blob/a9dc061d847277e30c5c6918d6de6f0606f9d285/docs/orchestration/docker-compose/docker-compose.yaml
        ]
      interval: 5s
      timeout: 5s
      retries: 10

volumes:
  minio_data:
