services:
  minio:
    image: minio/minio:RELEASE.2024-06-28T09-06-49Z
    command:
      - server
      - /data
      - --address=:9000
      - --console-address=:9001
    restart: always
    volumes:
      - minio_data:/data
    environment:
      - MINIO_ROOT_USER=${MINIO_ROOT_USER}
      - MINIO_ROOT_PASSWORD=${MINIO_ROOT_PASSWORD}
      - MINIO_UPDATE=off
    ports:
      - 9000:9000
      - 9001:9001

volumes:
  minio_data:
