apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component
images:
  - name: ghcr.io/whoisnian/k8s-example-backend-api # for base/backend-api
    newTag: v0.0.5
  - name: ghcr.io/whoisnian/k8s-example-backend-file # for base/backend-file
    newTag: v0.0.5
  - name: ghcr.io/whoisnian/k8s-example-frontend-static # for base/init-public
    newTag: v1.0.3
  - name: nginx # for base/frontend
    newTag: mainline-alpine
  - name: alpine # for base/init-node & base/init-public
    newTag: "3.17"
  - name: ghcr.io/whoisnian/feature-test # for base/init-node & base/init-public
    newTag: v0.0.7
