apiVersion: v1
kind: PersistentVolume
metadata:
  name: local-public-pv
spec:
  storageClassName: ""
  capacity:
    storage: 10Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete
  hostPath:
    path: /mnt/public
    type: Directory
