apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: uploads-pvc
spec:
  storageClassName: ""
  volumeName: uploads-pv
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
