apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
spec:
  replicas: 2
  template:
    spec:
      # affinity: # may affect feasible nodes scoring? https://kubernetes.io/docs/concepts/scheduling-eviction/kube-scheduler/
      #   podAffinity:
      #     requiredDuringSchedulingIgnoredDuringExecution:
      #       - labelSelector:
      #           matchLabels:
      #             k8s-example: node-init
      #         topologyKey: kubernetes.io/hostname
      containers:
        - image: reg.whoisnian.com/proxy.docker.io/library/nginx:TAG_SHOULD_NOT_EXIST
          command:
            ["/usr/sbin/nginx", "-p", "/app/html/", "-c", "/config/nginx.conf"]
          name: frontend
          ports:
            - containerPort: 8082
          volumeMounts:
            - name: nginx-config
              mountPath: /config
            - name: assets
              mountPath: /app/html/assets
            - name: local-public
              mountPath: /app/html
      volumes:
        - name: nginx-config
          configMap:
            name: nginx-config
            items:
              - key: NGINX_CONF
                path: nginx.conf
        - name: assets
          configMap:
            name: assets
        - name: local-public
          persistentVolumeClaim:
            claimName: local-public-pvc
