# 测试不同 deployment 下的不同 pod 是否复用 nfs 连接
apiVersion: v1
kind: Namespace
metadata:
  name: k8s-example
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: feature-test-1
  namespace: k8s-example
spec:
  replicas: 2
  selector:
    matchLabels:
      k8s-example: feature-test-1
  template:
    metadata:
      labels:
        k8s-example: feature-test-1
    spec:
      containers:
        - image: ghcr.io/whoisnian/feature-test:v0.0.7
          name: feature-test-1
          ports:
            - containerPort: 8080
          env:
            - name: CFG_PODNAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
          volumeMounts:
            - mountPath: /nfs
              name: nfs-test
      volumes:
        - name: nfs-test
          nfs:
            path: /
            server: 192.168.49.1
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: feature-test-2
  namespace: k8s-example
spec:
  replicas: 2
  selector:
    matchLabels:
      k8s-example: feature-test-2
  template:
    metadata:
      labels:
        k8s-example: feature-test-2
    spec:
      containers:
        - image: ghcr.io/whoisnian/feature-test:v0.0.7
          name: feature-test-2
          ports:
            - containerPort: 8080
          env:
            - name: CFG_PODNAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
          volumeMounts:
            - mountPath: /nfs
              name: nfs-test
      volumes:
        - name: nfs-test
          nfs:
            path: /tmp
            server: 192.168.49.1
