# 测试双 namespace 使用 ingress-nginx.canary 实现灰度上线
apiVersion: v1
kind: Namespace
metadata:
  name: k8s-example-1
---
apiVersion: v1
kind: Namespace
metadata:
  name: k8s-example-2
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: feature-test
  namespace: k8s-example-1
spec:
  replicas: 2
  selector:
    matchLabels:
      k8s-example: feature-test
  template:
    metadata:
      labels:
        k8s-example: feature-test
    spec:
      containers:
        - image: ghcr.io/whoisnian/feature-test:v0.0.7
          name: feature-test
          ports:
            - containerPort: 8080
          env:
            - name: CFG_PODNAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
---
apiVersion: v1
kind: Service
metadata:
  name: feature-test
  namespace: k8s-example-1
spec:
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
  selector:
    k8s-example: feature-test
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: feature-test
  namespace: k8s-example-2
spec:
  replicas: 2
  selector:
    matchLabels:
      k8s-example: feature-test
  template:
    metadata:
      labels:
        k8s-example: feature-test
    spec:
      containers:
        - image: ghcr.io/whoisnian/feature-test:v0.0.7
          name: feature-test
          ports:
            - containerPort: 8080
          env:
            - name: CFG_PODNAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
---
apiVersion: v1
kind: Service
metadata:
  name: feature-test
  namespace: k8s-example-2
spec:
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
  selector:
    k8s-example: feature-test
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-k8s-example-1
  namespace: k8s-example-1
  annotations:
    nginx.ingress.kubernetes.io/affinity: cookie
    nginx.ingress.kubernetes.io/affinity-mode: balanced
spec:
  ingressClassName: nginx
  rules:
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: feature-test
                port:
                  number: 8080
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-k8s-example-2
  namespace: k8s-example-2
  annotations:
    nginx.ingress.kubernetes.io/canary: "true"
    nginx.ingress.kubernetes.io/canary-by-cookie: canary
    nginx.ingress.kubernetes.io/canary-weight: "30"
spec:
  ingressClassName: nginx
  rules:
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: feature-test
                port:
                  number: 8080
