# 测试 pod 初始化 host 目录及 podAffinity 建立依赖关系
apiVersion: apps/v1
kind: Deployment
metadata:
  name: init-node
spec:
  replicas: 2
  selector:
    matchLabels:
      k8s-example: init-node
  template:
    metadata:
      labels:
        k8s-example: init-node
    spec:
      initContainers:
        - name: sleep-30
          image: ghcr.io/whoisnian/feature-test:v0.0.7
          command: ["sh", "-c", "sleep 30"]
          volumeMounts:
            - mountPath: /host-mnt
              name: host-mnt
      containers:
        - name: noop
          image: ghcr.io/whoisnian/feature-test:v0.0.7
          command: ["sh", "-c", "trap : TERM INT; sleep infinity & wait"]
      volumes:
        - name: host-mnt
          hostPath:
            path: /mnt/nonexistent
            type: Directory
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: init-public
spec:
  replicas: 2
  selector:
    matchLabels:
      k8s-example: init-public
  template:
    metadata:
      labels:
        k8s-example: init-public
    spec:
      affinity:
        podAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: k8s-example
                    operator: In
                    values: ["init-node"]
              topologyKey: kubernetes.io/hostname
      initContainers:
        - name: sleep-30
          image: ghcr.io/whoisnian/feature-test:v0.0.7
          command: ["sh", "-c", "sleep 30"]
      containers:
        - name: noop
          image: ghcr.io/whoisnian/feature-test:v0.0.7
          command: ["sh", "-c", "trap : TERM INT; sleep infinity & wait"]
