# 测试单 pod 多 containers 时的 pod 状态更新
apiVersion: apps/v1
kind: Deployment
metadata:
  name: feature-test
spec:
  replicas: 2
  selector:
    matchLabels:
      k8s-example: feature-test
  template:
    metadata:
      labels:
        k8s-example: feature-test
    spec:
      containers:
        - image: ghcr.io/whoisnian/feature-test:v0.0.7
          name: feature-test-1
          ports:
            - containerPort: 8080
          env:
            - name: CFG_MODEFILE
              value: "/config/mode8080"
          volumeMounts:
            - mountPath: /config/
              name: config
          resources:
            requests:
              memory: "256Mi"
            limits:
              memory: "512Mi"
        - image: ghcr.io/whoisnian/feature-test:v0.0.7
          name: feature-test-2
          ports:
            - containerPort: 8081
          env:
            - name: CFG_LISTENADDR
              value: "0.0.0.0:8081"
            - name: CFG_UPSTREAM
              value: "http://127.0.0.1:8080/upstream"
            - name: CFG_MODEFILE
              value: "/config/mode8081"
          volumeMounts:
            - mountPath: /config/
              name: config
          resources:
            requests:
              memory: "256Mi"
            limits:
              memory: "512Mi"
      restartPolicy: Always
      volumes:
        - name: config
          emptyDir: { medium: Memory }
---
apiVersion: v1
kind: Service
metadata:
  name: feature-test
spec:
  ports:
    - name: test1
      port: 8080
      targetPort: 8080
      protocol: TCP
      nodePort: 30001
    - name: test2
      port: 8081
      targetPort: 8081
      protocol: TCP
      nodePort: 30002
  selector:
    k8s-example: feature-test
  type: NodePort
