# 测试 emptyDir 内存占用触发 pod 的 OOM
apiVersion: v1
kind: Namespace
metadata:
  name: k8s-example
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: feature-test
  namespace: k8s-example
spec:
  replicas: 1
  selector:
    matchLabels:
      k8s-example: feature-test
  template:
    metadata:
      labels:
        k8s-example: feature-test
    spec:
      containers:
        - image: ghcr.io/whoisnian/feature-test:v0.0.7
          name: feature-test-1
          ports:
            - containerPort: 8080
          volumeMounts:
            - mountPath: /tmpfs/
              name: tmpfs
          resources:
            requests:
              memory: "100Mi"
            limits:
              memory: "200Mi"
        - image: ghcr.io/whoisnian/feature-test:v0.0.7
          name: feature-test-2
          ports:
            - containerPort: 8081
          env:
            - name: CFG_LISTENADDR
              value: "0.0.0.0:8081"
          volumeMounts:
            - mountPath: /tmpfs/
              name: tmpfs
          resources:
            requests:
              memory: "100Mi"
            limits:
              memory: "200Mi"
      volumes:
        - name: tmpfs
          emptyDir: { medium: Memory, sizeLimit: 100Mi }
---
apiVersion: v1
kind: Service
metadata:
  name: feature-test
  namespace: k8s-example
spec:
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
  selector:
    k8s-example: feature-test
