# 测试 NodePort 暴露服务
apiVersion: v1
kind: Namespace
metadata:
  name: k8s-example
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: feature-test
  namespace: k8s-example
spec:
  replicas: 4
  selector:
    matchLabels:
      k8s-example: feature-test
  template:
    metadata:
      labels:
        k8s-example: feature-test
    spec:
      containers:
        - image: ghcr.io/whoisnian/feature-test:v0.0.7
          name: feature-test
          ports:
            - containerPort: 8080
          env:
            - name: CFG_PODNAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
          resources:
            requests:
              memory: "256Mi"
            limits:
              memory: "1536Mi"
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: feature-test
  namespace: k8s-example
spec:
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
      nodePort: 30001
  selector:
    k8s-example: feature-test
  type: NodePort
