apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component
images:
  - name: "reg.whoisnian.com/k8s-example/frontend"
    newTag: "v0.0.3"
  - name: "reg.whoisnian.com/k8s-example/backend-api"
    newTag: "v0.0.3"
  - name: "reg.whoisnian.com/k8s-example/backend-file"
    newTag: "v0.0.2"
