apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: init-node
spec:
  template:
    spec:
      initContainers:
        - name: prepare-dirs
          image: alpine:TAG_SHOULD_NOT_EXIST
          command: ["install", "--mode=0755", "--directory", "/host-mnt/public"] # --owner=500 --group=500
          volumeMounts:
            - mountPath: /host-mnt
              name: host-mnt
      containers:
        - name: pong
          image: ghcr.io/whoisnian/feature-test:TAG_SHOULD_NOT_EXIST
          ports:
            - containerPort: 8080
      volumes:
        - name: host-mnt
          hostPath:
            path: /mnt
            type: Directory
