apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: init-node
spec:
  template:
    spec:
      initContainers:
        - name: prepare-dirs
          image: reg.whoisnian.com/proxy.docker.io/library/alpine:TAG_SHOULD_NOT_EXIST
          command: ["install", "--mode=0755", "--directory", "/host-mnt/public"] # --owner=500 --group=500
          volumeMounts:
            - mountPath: /host-mnt
              name: host-mnt
      containers:
        - name: noop
          image: reg.whoisnian.com/proxy.docker.io/library/alpine:TAG_SHOULD_NOT_EXIST
          command: ["sh", "-c", "trap : TERM INT; sleep infinity & wait"]
      volumes:
        - name: host-mnt
          hostPath:
            path: /mnt
            type: Directory
