apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: init-public
spec:
  template:
    spec:
      initContainers:
        - name: prepare-dirs
          image: reg.whoisnian.com/proxy.docker.io/library/alpine:TAG_SHOULD_NOT_EXIST
          command: ["sh", "/scripts/prepare-dirs.sh"]
          volumeMounts:
            - mountPath: /public
              name: local-public
            - mountPath: /scripts
              name: scripts
        - name: cp-frontend-static
          image: reg.whoisnian.com/k8s-example/frontend:TAG_SHOULD_NOT_EXIST
          command: ["cp", "-r", "/app/html/.", "-t", "/public"]
          volumeMounts:
            - mountPath: /public
              name: local-public
      containers:
        - name: noop
          image: reg.whoisnian.com/proxy.docker.io/library/alpine:TAG_SHOULD_NOT_EXIST
          command: ["sh", "-c", "trap : TERM INT; sleep infinity & wait"]
      volumes:
        - name: local-public
          persistentVolumeClaim:
            claimName: local-public-pvc
        - name: scripts
          configMap:
            name: scripts
