apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-api
spec:
  replicas: 2
  selector:
    matchLabels:
      k8s-example: backend-api
  template:
    metadata:
      labels:
        k8s-example: backend-api
    spec:
      containers:
        - image: reg.whoisnian.com/k8s-example/backend-api:v0.0.4
          name: backend-api
          ports:
            - containerPort: 8080
          env:
            - name: CFG_FILEPREFIX
              value: http://backend-file:8081
            - name: CFG_MYSQLDSN
              valueFrom:
                secretKeyRef:
                  name: mysql-dsn
                  key: dsnStr
                  optional: false
      restartPolicy: Always
