apiVersion: v1
kind: Service
metadata:
  labels:
    app: k8s-example
    tier: backend-file
  name: backend-file
spec:
  ports:
  - port: 8081
    targetPort: 8081
    protocol: TCP
  selector:
    app: k8s-example
    tier: backend-file