apiVersion: v1
kind: Service
metadata:
  labels:
    app: k8s-example
    tier: backend-api
  name: backend-api
spec:
  type: NodePort
  ports:
  - port: 8080
    targetPort: 8080
    nodePort: 30080
    protocol: TCP
  selector:
    app: k8s-example
    tier: backend-api