apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-api
spec:
  replicas: 2
  selector:
    matchLabels:
      k8s-example: backend-api
  template:
    metadata:
      labels:
        k8s-example: backend-api
    spec:
      containers:
        - image: reg.whoisnian.com/k8s-example/backend-api:v0.0.2
          name: backend-api
          ports:
            - containerPort: 8080
          env:
            - name: FILE_PREFIX
              value: http://backend-file:8081
            - name: MYSQL_DSN
              value: k8s:KxY8cSAWz1WJEfs3@tcp(external-database:3306)/k8s
      restartPolicy: Always
