apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-file
spec:
  replicas: 4
  selector:
    matchLabels:
      app: k8s-example
      tier: backend-file
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: k8s-example
        tier: backend-file
    spec:
      containers:
        - image: reg.whoisnian.com/k8s-example/backend-file:v0.0.1
          name: backend-file
          ports:
            - containerPort: 8081
          env:
            - name: API_PREFIX
              value: http://backend-api:8080
          resources:
            requests:
              cpu: 100m
              memory: 100Mi
          volumeMounts:
            - mountPath: /app/uploads
              name: uploads
      restartPolicy: Always
      volumes:
        - name: uploads
          persistentVolumeClaim:
            claimName: uploads