apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      k8s-example: frontend
  template:
    metadata:
      labels:
        k8s-example: frontend
    spec:
      containers:
        - image: reg.whoisnian.com/k8s-example/frontend:v0.0.2
          name: frontend
          ports:
            - containerPort: 8082
      restartPolicy: Always
