apiVersion: v1
kind: Service
metadata:
  labels:
    k8s-example: frontend
  name: frontend
spec:
  ports:
    - port: 8082
      targetPort: 8082
      protocol: TCP
  selector:
    k8s-example: frontend
