apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: uploads
spec:
  storageClassName: ""
  volumeName: uploads
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
