apiVersion: v1
kind: PersistentVolume
metadata:
  name: uploads
spec:
  storageClassName: ""
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  nfs:
    server: 192.168.49.1
    path: /
