# 测试 pod 利用 initContainers 强制设定启动顺序
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: init-node
spec:
  selector:
    matchLabels:
      k8s-example: init-node
  template:
    metadata:
      labels:
        k8s-example: init-node
    spec:
      initContainers:
        - name: sleep-20
          image: ghcr.io/whoisnian/feature-test:v0.0.7
          command: ["sh", "-c", "sleep 20"]
      containers:
        - name: pong
          image: ghcr.io/whoisnian/feature-test:v0.0.7
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  labels:
    k8s-example: init-node-svc
  name: init-node-svc
spec:
  internalTrafficPolicy: Local
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
  selector:
    k8s-example: init-node
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: init-public
spec:
  selector:
    matchLabels:
      k8s-example: init-public
  template:
    metadata:
      labels:
        k8s-example: init-public
    spec:
      initContainers:
        - name: ping
          image: ghcr.io/whoisnian/feature-test:v0.0.7
          command: [
              "sh",
              "-c", # "for i in {1..10}; do echo $i; sleep 0.2; done" in alpine.sh will output "{1..10}"
              "for i in $(seq 1 10); do sleep 3; if wget -O- init-node-svc:8080/ping; then exit 0; fi; done; exit 1",
            ]
        - name: sleep-20
          image: ghcr.io/whoisnian/feature-test:v0.0.7
          command: ["sh", "-c", "sleep 20"]
      containers:
        - name: noop
          image: ghcr.io/whoisnian/feature-test:v0.0.7
          command: ["sh", "-c", "trap : TERM INT; sleep infinity & wait"]
