commonLabels:
  k8s-example: frontend
resources:
  - ./frontend-deployment.yaml
  - ./frontend-service.yaml
configMapGenerator:
  - name: nginx-config
    files:
      - NGINX_CONF=nginx.prod.conf
  - name: assets
    files:
      - ./assets/about.json
      - ./assets/nyancat.png
